### ISSUE TITLE
Deploy Celery through Supervisor

### ISSUE THREAD

**Issue by kalxas** [PublicaMundi/labs.geodata.gov.gr#98]
Moved from #75

**Comment by drmalex07** [comment]
I suggest that we replace this one by a conventional init.d-style script that starts/stops a `celery` master process (which in turn handles the group of (managed) worker processes).

Why? Because  `supervisor` blindly sends the `TERM` signal to all it's managed processes (as it is not aware of a master process). This will immediatelly stop active tasks, and can leave them in a corrupt state: aknowledged as "started", never finished.

**Comment by kalxas** [comment]
Done with init.d
